# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6fa2405c5474eef0875b1d23bce4889b5cd0466cb66409bf8cf87b8bfebf8954bed3a1b237ed2d3d8155e4ba58c5859dd070400fa4b373d9a9c82fc5fc8b667

test:
  secret_key_base: e4098cc3de606da5ca79d40c1e93251f3766eaeb9ead70f78e64c9118aa99f59538e0fcf11605ac4c730b21949c87ed96396b9c8ca0b44d24e9bb808dfcb00b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
